### PR TITLE
Add Expanded Groove MIDI Dataset

### PR DESCRIPTION
**Pull request by cghawthorne**

### CODE REVIEW

**Comment by cghawthorne** [comment]
I don't think the test failure is related to this PR. It looks like it might just be a timeout. Is there anything else needed from me for this PR?

**Comment by sebastianrosenzweig** [comment]
#35 might solve this issue.

**Comment by cghawthorne** [comment]
Thanks @sebastianrosenzweig! I'll rebase this PR once yours is in.

**Comment by stefan-balke** [comment]
You can do it now!

**Comment by cghawthorne** [comment]
@stefan-balke thanks! I've rebased my change, regenerated the outputs, and now all the tests pass!

**Comment by cghawthorne** [comment]
Quick ping on this, the change should be all ready to go now.

**Comment by stefan-balke** [comment]
Yes, thanks for the ping! Merged!

**Pull request merged**
