### PR TITLE
Add MSMD dataset

### PR DESCRIPTION
**Pull request by stefan-balke**

### CODE REVIEW

**Comment by lostanlen** [comment]
Hi @stefan-balke, are you sure that you want to give a link to the GitHub CPJKU/msmd?
Why not directly the Zenodo page? https://zenodo.org/record/2597505/
The former may go 404 one day; the latter won't.

**Comment by stefan-balke** [comment]
Yes, either or is fine. IMHO, you need both for this dataset.

**Comment by lostanlen** [comment]
Then it would be good to bundle the v1.1 code on Zenodo alongside the ZIP file?

**Comment by ejhumphrey** [comment]
to be fair, they both may 404 someday, because the internet is an ephemeral web of transience.

but! this raises an interesting limitation of the schema – what if there are mirrors? or multiple related sites? should `url` be an array? or do we need a separate `mirrors` or `additional_urls` field? I've added #17 for that discussion. I'm fine with leaving these changes as-is, and revisiting what to do with multiple URLs going forward.

**Comment by ejhumphrey** [comment]
doing a little cleaning on this, @lostanlen or @stefan-balke do you have any updated opinions on this?

**Pull request closed without merging**
